baseurl: "https://movie-which.netlify.app"
title: "Кино которое"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
uglyURLs: false
metaDataFormat: "yaml"
params:
  itunes: https://itunes.apple.com/podcast/id123456789
  android: /index.xml
  feed: /index.xml
  desc: Подкаст о кино, в котором ничего не понятно
  summary: Странное кино с налетом гениальности, которое обсуждают ведущие с зубным налетом
  StaticURL: "https://movie-which.netlify.app"
permalinks:
  post: "/:title"
